- name: play 1
  hosts: vagrantvm1
  remote_user: ubuntu
  become: true
  vars:
    create_containers: 4
    default_container_name: vue-app
    default_container_image: naufalafif58/vue-crud-example
    default_container_exposed_port: 8888

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: check container stat
      command: "curl localhost:{{default_container_exposed_port}}"
      failed_when: false
      register: container_stat

    - name: app container
      command: sudo docker run -d --name {{default_container_name}} -p {{default_container_exposed_port}}:80 {{default_container_image}}
      when: >
        "Connection refused" in container_stat.stderr

